### ISSUE TITLE
IPanda50 not downloading

### ISSUE THREAD

**Issue by mfruhner** [WildlifeDatasets/wildlife-datasets#3] opened 2024-01-13 14:05 UTC
Hey,
I also tried downloading IPanda50, but from all my machines I get:

```
Cannot retrieve the public link of the file. You may need to change
the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1nkh-g6a8JvWy-XsMaZqrN2AXoPlaXuFg 
```

The stated link works however.. any idea?

**Comment by sadda** [comment] 2024-01-17 08:10
This is unfortunate :( The problem is too many accesses for the Google Drive link as written in the description. I have updated the error message so that it is clearer.

The only solution I can think of is to reupload the dataset somewhere else. Even though the dataset license allows for that, I would like to evade it for as long as possible. If you manage to come up with any other solution, let me know please :)

**Comment by sadda** [comment] 2024-10-31 09:41
Since this seems to be an external problem, and there were no further comments, I am closing this issue.

**Closed by sadda** 2024-10-31 09:41 UTC
